import type { ReactNode } from 'react';
import type { Metadata, Viewport } from 'next';
import { headers } from 'next/headers';
import { site } from '@/lib/site';

import '@/styles/tokens.css';
import '@/styles/base.css';
import '@/styles/components.css';
import '@/styles/additions.css';

/**
 * Root layout. next-intl owns <html> in `[locale]/layout.tsx` so that `lang`
 * and `dir` are always correct for the rendered locale; this file only exists
 * to satisfy Next's required root and must not emit markup of its own.
 *
 * The global stylesheets are imported HERE and not in `[locale]/layout.tsx`
 * because the root not-found page renders outside `[locale]` — CSS imported
 * in `not-found.tsx` itself is silently dropped by Next 14.2, so the root
 * layout is the only place that styles every route AND the 404.
 */
/**
 * Icon set + manifest are declared at the root so the 404 outside `[locale]`
 * carries them too. All eight files are generated by `npm run build:icons`,
 * which also guards brandHex against drifting from --p-700.
 */
export const metadata: Metadata = {
  metadataBase: new URL(site.url),
  icons: {
    icon: [
      { url: '/favicon.svg', type: 'image/svg+xml' },
      { url: '/favicon.ico', sizes: '48x48 32x32 16x16' },
      { url: '/icon-192.png', type: 'image/png', sizes: '192x192' },
      { url: '/icon-512.png', type: 'image/png', sizes: '512x512' }
    ],
    apple: [{ url: '/apple-touch-icon.png', sizes: '180x180' }]
  },
  manifest: '/manifest.webmanifest'
};

/** brandHex, not a token: theme-color is parsed before any stylesheet loads. */
export const viewport: Viewport = {
  themeColor: site.brandHex
};

export default function RootLayout({ children }: { children: ReactNode }) {
  // Reading the request headers opts EVERY page into dynamic rendering — the
  // price of the nonce-based CSP the middleware mints. A per-request nonce
  // cannot exist in prerendered HTML: with static pages the served inline
  // bootstrap scripts carried no nonce (measured: 15 of them) and the browser
  // blocked hydration site-wide. Dynamic rendering lets Next stamp the nonce
  // it finds on the request's Content-Security-Policy header onto every
  // script tag it emits.
  headers();
  return children;
}
